import "./globals.css";
import { Outfit } from 'next/font/google'
 
// If loading a variable font, you don't need to specify the font weight
const outfit = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: "Blog Post Website",
  description: "Generated By Eng Mohamed Del",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      {/* <style data-next-hide-fouc="false"> */}

      <body className={outfit.className}>
        {children}
      </body>
      {/* </style> */}
    </html>
  );
}
